services:
  app:
    build: .
    container_name: Cast-Inspection-
    user: myuser
    command: uvicorn src.main:app --host 0.0.0.0 --port 4000 --reload
    ports:
      - "4000:4000"
    volumes:
      - ./src:/code/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
